#!/usr/bin/env bash
set -x

TAG=${GITHUB_REF#refs/*/v}
ARCH=x86_64

if [[ "${OS}" == "macOS-latest" ]]; then
    VENDOR=apple
    OS=darwin
else
    VENDOR=unknown
    OS=linux
fi

chmod 755 target/release/${PROGRAM_NAME}
echo "RELEASE_NAME=${PROGRAM_NAME}-${TAG}-${ARCH}-${VENDOR}-${OS}" >> $GITHUB_ENV
