#!/usr/bin/env bash

ARCH=x86_64

if [[ "${OS}" == "macOS-latest" ]]; then
    VENDOR=apple
    OS=darwin
else
    VENDOR=unknown
    OS=linux
fi

mv target/debug/verticareader target/verticareader-${TRAVIS_TAG}-${ARCH}-${VENDOR}-${OS}
chmod 755 target/verticareader-${TRAVIS_TAG}-${ARCH}-${VENDOR}-${OS}
