#!/usr/bin/env bash
set -x

env

TAG=${GITHUB_REF#refs/*/v}
ARCH=x86_64

if [[ "${OS}" == "macOS-latest" ]]; then
    VENDOR=apple
    OS=darwin
else
    VENDOR=unknown
    OS=linux
fi

# mv target/release/ac target/ac-${TAG}-${ARCH}-${VENDOR}-${OS}
# chmod 755 target/ac-${TAG}-${ARCH}-${VENDOR}-${OS}

chmod 755 target/release/ac
echo "RELEASE_NAME=ac-${TAG}-${ARCH}-${VENDOR}-${OS}" >> $GITHUB_ENV
