#!/usr/bin/env bash
set -x

ARCH=x86_64

if [[ "${OS}" == "macOS-latest" ]]; then
    VENDOR=apple
    OS=darwin
else
    VENDOR=unknown
    OS=linux
fi

mv target/debug/verticareader target/ac-${TAG}-${ARCH}-${VENDOR}-${OS}
chmod 755 target/ac-${TAG}-${ARCH}-${VENDOR}-${OS}
